variables:
  GIT_STRATEGY: clone
  GIT_SUBMODULE_STRATEGY: recursive
  GIT_SUBMODULE_FORCE_HTTPS: "true" # Force git to clone submodules with HTTPS

tests:
  image: $TIQI_PODMAN_IMAGES_URL/python:3.10
  tags:
    - podman
  script:
    - poetry install
    - make test-notebooks
