[tool.poetry]
name = "pytrans-models"
version = "0.1.0"
description = "Examples and showcase repo for waveform generation in actual traps with pytrans"
authors = ["cmordini <cmordini@phys.ethz.ch>"]
packages = [
     { include = "models"},
  ]

[tool.poetry.dependencies]
python = ">=3.9,<3.10"
pytrans = {path = "deps/pytrans", develop = true}
ipykernel = "^6.9.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
